;;;; SPDX-License-Identifier: BSD-3-Clause
(in-package #:prime-candidate)
(declaim (optimize (speed 3) (safety 0) (debug 0)))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown sparse-kernel! (sb-sys:system-area-pointer (unsigned-byte 64) (unsigned-byte 64) (unsigned-byte 64) (integer 1 15))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (sparse-kernel!)
    (:translate sparse-kernel!) (:policy :fast-safe)
    ;; Keep inputs live until all temporary-register computations finish.
    (:args (sap :scs (sb-vm::sap-reg) :to :save)
           (blocks :scs (sb-vm::unsigned-reg) :to :save)
           (q :scs (sb-vm::unsigned-reg) :to :save)
           (step :scs (sb-vm::unsigned-reg) :to :save))
    (:arg-types sb-vm::system-area-pointer sb-vm::unsigned-num sb-vm::unsigned-num sb-vm::unsigned-num (:constant (integer 1 15)))
    (:info residue)
    (:temporary (:sc sb-vm::sap-reg) ptr)
    (:temporary (:sc sb-vm::unsigned-reg) remaining q3 q5 q7)
    (:generator 1
      (let ((again (sb-assem:gen-label)) (done (sb-assem:gen-label)))
        (sb-vm::move ptr sap)
        (sb-vm::move remaining blocks)
        (sb-assem:inst test remaining remaining)
        (sb-assem:inst jmp :z done)
        (sb-assem:inst lea q3 (sb-vm::ea 0 q q 2))
        (sb-assem:inst lea q5 (sb-vm::ea 0 q q 4))
        (sb-assem:inst lea q7 (sb-vm::ea 0 q3 q 4))
        (sb-assem:emit-label again)
        (loop for k below 8 for index in (list nil q q q3 q q5 q3 q7)
              for scale in '(1 1 2 1 4 1 2 1)
              for carry = (floor (+ (floor residue 2) (* k (mod residue 8))) 8)
              for mask = (ash 1 (mod (+ (floor residue 2) (* k residue)) 8))
              do (sb-assem:inst or :byte (sb-vm::ea carry ptr index scale) mask))
        (sb-assem:inst add ptr step)
        (sb-assem:inst dec remaining)
        (sb-assem:inst jmp :nz again)
        (sb-assem:emit-label done)))))
(defmacro define-kernel-resetters ()
  `(progn
     ,@(loop for r from 1 to 15 by 2 for name = (intern (format nil "SPARSE-~D" r))
             collect
             `(defun ,name (bits nbytes factor)
                (declare (type words bits) (type fixnum nbytes) (type (integer 3 2147483647) factor))
                (let* ((first (ash factor -4)) (start (* first factor)) (q (ash factor -3))
                       (blocks (floor (- nbytes start) factor))
                       (tail (+ start first (* blocks factor))))
                  (declare (type (unsigned-byte 59) first start q blocks tail))
                  (sb-sys:with-pinned-objects (bits)
                    (let ((sap (sb-sys:vector-sap bits)))
                      (sparse-kernel! (sb-sys:sap+ sap (+ start first)) blocks q factor ,r)
                      ,@(loop for k below 8
                              for carry = (floor (+ (floor r 2) (* k (mod r 8))) 8)
                              for mask = (ash 1 (mod (+ (floor r 2) (* k r)) 8))
                              collect `(let ((index (+ tail (* ,k q) ,carry)))
                                         (declare (type (unsigned-byte 59) index))
                                         (when (< index nbytes) (or-byte! sap index ,mask)))))))
                nil))))
(define-kernel-resetters)
(setf *name* "echologie-cl-sparse-kernel")
