;;;; SPDX-License-Identifier: BSD-3-Clause
(in-package #:prime-candidate)
(declaim (optimize (speed 3) (safety 0) (debug 0)))
(declaim (sb-ext:muffle-conditions sb-ext:compiler-note))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown dense-kernel! (sb-sys:system-area-pointer (unsigned-byte 64) (integer 3 129))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (dense-kernel!)
    (:translate dense-kernel!) (:policy :fast-safe)
    (:args (sap :scs (sb-vm::sap-reg) :to :save)
           (nwords :scs (sb-vm::unsigned-reg) :to :save))
    (:arg-types sb-vm::system-area-pointer sb-vm::unsigned-num (:constant (integer 3 129)))
    (:info factor)
    (:temporary (:sc sb-vm::sap-reg) ptr)
    (:temporary (:sc sb-vm::unsigned-reg) remaining mask0 mask1 mask2)
    (:generator 1
      (let* ((groups (make-array factor :initial-element nil))
             (first (* factor (floor factor 128)))
             (again (sb-assem:gen-label)) (tail (sb-assem:gen-label)))
        ;; Generate the same individual multiples as the Rust/Lisp dense loop.
        ;; Associative ORs within one word are folded during code generation.
        (dotimes (k 64)
          (let ((bit (+ (floor factor 2) (* k factor))))
            (push (ash 1 (mod bit 64)) (aref groups (floor bit 64)))))
        (let ((masks (map 'vector (lambda (bits) (reduce #'logior bits :initial-value 0)) groups)))
          (sb-assem:inst lea ptr (sb-vm::ea (* 8 first) sap))
          (sb-vm::move remaining nwords)
          (unless (zerop first) (sb-assem:inst sub remaining first))
          (when (= factor 3)
            (loop for reg in (list mask0 mask1 mask2) for value across masks
                  do (sb-assem:inst mov reg value)))
          (flet ((emit-word (i)
                   (let ((mask (aref masks i)))
                     (unless (zerop mask)
                       (cond ((= factor 3)
                              (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr)
                                             (nth i (list mask0 mask1 mask2))))
                             ((typep mask '(signed-byte 32))
                              (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) mask))
                             (t (sb-assem:inst mov mask0 mask)
                                (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) mask0)))))))
            (sb-assem:inst cmp remaining factor)
            (sb-assem:inst jmp :b tail)
            (sb-assem:emit-label again)
            (dotimes (i factor) (emit-word i))
            (sb-assem:inst add ptr (* factor 8))
            (sb-assem:inst sub remaining factor)
            (sb-assem:inst cmp remaining factor)
            (sb-assem:inst jmp :ae again)
            (sb-assem:emit-label tail)
            (dotimes (i factor)
              (unless (zerop (aref masks i))
                (let ((skip (sb-assem:gen-label)))
                  (sb-assem:inst cmp remaining i)
                  (sb-assem:inst jmp :be skip)
                  (emit-word i)
                  (sb-assem:emit-label skip)))))
          (let* ((bit (floor factor 2))
                 (clear (logxor #xffffffffffffffff (ash 1 (mod bit 64)))))
            (sb-assem:inst mov mask0 clear)
            (sb-assem:inst and :qword (sb-vm::ea (* 8 (floor bit 64)) sap) mask0)))))))
(defmacro define-dense-kernels ()
  `(progn
     ,@(loop for p from 3 to 129 by 2 collect
             `(defun ,(intern (format nil "DENSE-~D" p)) (bits)
                (declare (type words bits))
                (sb-sys:with-pinned-objects (bits)
                  (dense-kernel! (sb-sys:vector-sap bits) (length bits) ,p))
                nil))))
(define-dense-kernels)
(setf *name* "echologie-cl-dense-sparse-kernels")
