;;;; Fresh, odd-only Eratosthenes sieve. BSD-3-Clause.
(defpackage #:prime-candidate
  (:use #:cl)
  (:export #:make-sieve #:run-sieve #:primep #:count-primes #:*tags* #:*name*))
(in-package #:prime-candidate)
(declaim (optimize (speed 3) (safety 0) (debug 1)))
(defparameter *name* "echologie-cl-batch-words")
(defparameter *tags* "algorithm=base,faithful=yes,bits=1")
(deftype words () '(simple-array (unsigned-byte 64) (*)))
(defclass sieve-state ()
  ((limit :initarg :limit :reader sieve-limit :type fixnum)
   (bits :initarg :bits :reader sieve-bits :type words)))
(defun make-sieve (limit)
  "Allocate a fresh instance and its own runtime-sized bit storage."
  (check-type limit (integer 0 #.most-positive-fixnum))
  (let ((bits (make-array (ceiling limit 128) :element-type '(unsigned-byte 64)
                         :initial-element 0)))
    (when (plusp (length bits)) (setf (aref bits 0) 1))
    (make-instance 'sieve-state :limit limit :bits bits)))
(declaim (inline marked-p mark))
(defun marked-p (words index)
  (declare (type words words) (type fixnum index))
  (logbitp (logand index 63) (aref words (ash index -6))))
(defun mark (words index)
  (declare (type words words) (type fixnum index))
  (let ((word-index (ash index -6)))
    (setf (aref words word-index)
          (logior (aref words word-index)
                  (the (unsigned-byte 64) (ash 1 (logand index 63)))))))
(defun run-sieve (sieve)
  (let* ((words (sieve-bits sieve)) (limit (sieve-limit sieve))
         (size (ceiling limit 2)))
    (declare (type words words) (type fixnum limit size))
    (loop for factor fixnum from 3 to (isqrt limit) by 2
          unless (marked-p words (ash factor -1))
            do (loop for index fixnum from (ash (* factor factor) -1)
                     below size by factor do (mark words index))))
  sieve)
(defun primep (sieve number)
  (declare (type fixnum number))
  (and (<= 2 number (the fixnum (sieve-limit sieve)))
       (or (= number 2)
           (and (oddp number)
                (not (marked-p (sieve-bits sieve) (ash number -1)))))))
(defun count-primes (sieve)
  (let* ((words (sieve-bits sieve)) (limit (sieve-limit sieve))
         (size (ceiling limit 2)) (full (ash size -6))
         (remainder (logand size 63)) (composites 0))
    (declare (type words words) (type fixnum limit size full remainder composites))
    (dotimes (i full) (incf composites (logcount (aref words i))))
    (when (plusp remainder)
      (incf composites
            (logcount (logand (aref words full)
                             (1- (ash 1 remainder))))))
    (+ (if (>= limit 2) 1 0) (- size composites))))
