;;;; Fresh, odd-only Eratosthenes sieve. BSD-3-Clause.
(defpackage #:prime-candidate
  (:use #:cl)
  (:export #:make-sieve #:run-sieve #:primep #:count-primes #:*tags* #:*name*))
(in-package #:prime-candidate)
(declaim (optimize (speed 3) (safety 0) (debug 1)))
(defparameter *name* "echologie-cl-batch-dense129")
(defparameter *tags* "algorithm=base,faithful=yes,bits=1")
(deftype words () '(simple-array (unsigned-byte 64) (*)))
(defclass sieve-state ()
  ((limit :initarg :limit :reader sieve-limit :type fixnum)
   (bits :initarg :bits :reader sieve-bits :type words)))
(defun make-sieve (limit)
  "Allocate a fresh instance and its own runtime-sized bit storage."
  (check-type limit (integer 0 #.most-positive-fixnum))
  (let ((bits (make-array (ceiling limit 128) :element-type '(unsigned-byte 64)
                         :initial-element 0)))
    (when (plusp (length bits)) (setf (aref bits 0) 1))
    (make-instance 'sieve-state :limit limit :bits bits)))
(declaim (inline marked-p mark))
(defun marked-p (words index)
  (declare (type words words) (type fixnum index))
  (logbitp (logand index 63) (aref words (ash index -6))))
(defun mark (words index)
  (declare (type words words) (type fixnum index))
  (let ((word-index (ash index -6)))
    (setf (aref words word-index)
          (logior (aref words word-index)
                  (the (unsigned-byte 64) (ash 1 (logand index 63)))))))
;;; Code-generation analogue of the dense resetters in Mike Barber's and
;;; GordonBGood's Rust hybrid: every source operation marks one composite bit.
;;; The compiler may combine adjacent constant OR operations in one word.
(defmacro define-dense-resetters (maximum)
  `(progn
     ,@(loop for factor from 3 to maximum by 2
             for name = (intern (format nil "DENSE-~D" factor))
             for first-word = (* factor (floor (floor (* factor factor) 2)
                                                 (* 64 factor)))
             collect
             (let ((groups (make-array factor :initial-element nil)))
               (dotimes (i 64)
                 (let ((index (+ (floor factor 2) (* i factor))))
                   (push (ash 1 (mod index 64)) (aref groups (floor index 64)))))
               (flet ((word-form (offset masks)
                        `(let ((word (aref words (+ base ,offset))))
                           (declare (type (unsigned-byte 64) word))
                           ,@(loop for mask in (reverse masks)
                                   collect `(setf word (logior word ,mask)))
                           (setf (aref words (+ base ,offset)) word))))
                 `(defun ,name (words)
                    (declare (type words words))
                    (let ((base ,first-word) (end (length words)))
                      (declare (type fixnum base end))
                      (loop while (<= (+ base ,factor) end)
                            do ,@(loop for masks across groups for i from 0
                                       when masks collect (word-form i masks))
                               (incf base ,factor))
                      ,@(loop for masks across groups for i from 0 when masks
                              collect `(when (< (+ base ,i) end)
                                         ,(word-form i masks)))
                      ;; Dense alignment can include the factor itself.
                      (setf (aref words ,(floor (floor factor 2) 64))
                            (logandc2 (aref words ,(floor (floor factor 2) 64))
                                      ,(ash 1 (mod (floor factor 2) 64)))))
                    (values)))))))
(define-dense-resetters 129)
(defmacro dense-dispatch (factor words fallback)
  `(case ,factor
     ,@(loop for p from 3 to 129 by 2
             collect `(,p (,(intern (format nil "DENSE-~D" p)) ,words)))
     (otherwise ,fallback)))

(defun run-sieve (sieve)
  (let* ((words (sieve-bits sieve)) (limit (sieve-limit sieve))
         (size (ceiling limit 2)))
    (declare (type words words) (type fixnum limit size))
    (loop for factor fixnum from 3 to (isqrt limit) by 2
          unless (marked-p words (ash factor -1))
            do (dense-dispatch factor words
                 (loop for index fixnum from (ash (* factor factor) -1)
                       below size by factor do (mark words index)))))
  sieve)
(defun primep (sieve number)
  (declare (type fixnum number))
  (and (<= 2 number (the fixnum (sieve-limit sieve)))
       (or (= number 2)
           (and (oddp number)
                (not (marked-p (sieve-bits sieve) (ash number -1)))))))
(defun count-primes (sieve)
  (let* ((words (sieve-bits sieve)) (limit (sieve-limit sieve))
         (size (ceiling limit 2)) (full (ash size -6))
         (remainder (logand size 63)) (composites 0))
    (declare (type words words) (type fixnum limit size full remainder composites))
    (dotimes (i full) (incf composites (logcount (aref words i))))
    (when (plusp remainder)
      (incf composites
            (logcount (logand (aref words full)
                             (1- (ash 1 remainder))))))
    (+ (if (>= limit 2) 1 0) (- size composites))))
