;;;; SPDX-License-Identifier: BSD-3-Clause
;;;; Load after the candidate and the unchanged benchmark harness.
(defpackage #:prime-lab (:use #:cl) (:nicknames #:lab)
  (:export #:apply-file #:measure #:restore #:cost #:*campaign*))
(in-package #:prime-lab)
(defparameter *campaign* #p"campaign-2026-09-13-followup/")
(defparameter *manifest* (merge-pathnames "active-manifest.sexp" *campaign*))
(defun record-event (event)
  (with-open-file (out (merge-pathnames "costs.sexp" *campaign*)
                       :direction :output :if-exists :append :if-does-not-exist :create)
    (let ((*print-pretty* nil))
      (write (list* :utc (get-universal-time) event) :stream out)
      (terpri out) (finish-output out))))
(defmacro cost (label &body body)
  `(let ((start (get-internal-real-time)) (cpu (get-internal-run-time)))
     (unwind-protect (progn ,@body)
       (record-event (list :phase ,label
                          :wall-seconds (/ (- (get-internal-real-time) start) (float internal-time-units-per-second 1d0))
                          :cpu-seconds (/ (- (get-internal-run-time) cpu) (float internal-time-units-per-second 1d0)))))))
(defun digest (file)
  (let ((line (with-output-to-string (out)
                (sb-ext:run-program "/usr/bin/sha256sum" (list (namestring file)) :output out))))
    (subseq line 0 64)))
(defun manifest ()
  (if (probe-file *manifest*)
      (with-open-file (in *manifest*) (let ((*read-eval* nil)) (read in))) nil))
(defun apply-file (file)
  "Save source identity, compile/load/check, then remember the successful FASL."
  (let* ((hash (digest file))
         (fasl (pathname (format nil ".build/followup/~A.fasl" hash))))
    (ensure-directories-exist fasl)
    (record-event (list :phase :start :source file :sha256 hash))
    (handler-case
        (progn
          (cost (list :compile file)
            (multiple-value-bind (output warnings failure)
                (compile-file file :output-file fasl :verbose nil :print nil)
              (declare (ignore output warnings))
              (when failure (error "Compilation failed: ~A" file))))
          (cost (list :load file) (load fasl))
          (cost (list :check file) (prime-bench:check-candidate))
          (let ((entries (append (manifest) (list (list :source file :sha256 hash :fasl fasl)))))
            (let ((pending (make-pathname :type "pending" :defaults *manifest*)))
              (with-open-file (out pending :direction :output :if-exists :supersede
                                           :if-does-not-exist :create)
                (write entries :stream out))
              (assert (sb-unix:unix-rename (namestring pending) (namestring *manifest*)))))
          (record-event (list :phase :accepted :source file :sha256 hash))
          (format t "~&APPLIED ~A~%" file) t)
      (error (e) (record-event (list :phase :error :source file :message (princ-to-string e)))
                 (format t "~&FAILED ~A: ~A~%" file e)))))
(defun restore ()
  (cost :restore-deltas
    (dolist (entry (manifest))
      (assert (equal (getf entry :sha256) (digest (getf entry :source))))
      (unless (probe-file (getf entry :fasl))
        (ensure-directories-exist (getf entry :fasl))
        (cost (list :rebuild (getf entry :source))
          (multiple-value-bind (output warnings failed)
              (compile-file (getf entry :source) :output-file (getf entry :fasl)
                            :verbose nil :print nil)
            (declare (ignore output warnings))
            (assert (not failed)))))
      (load (getf entry :fasl))))
  (prime-bench:check-candidate)
  (format t "~&RESTORED ~D deltas~%" (length (manifest))))
(defun measure (&optional (seconds 5d0) (repeats 3))
  (cost (list :measure prime-candidate:*name* seconds repeats)
    (prime-bench:measure :seconds seconds :repeats repeats)))
