;;;; SPDX-License-Identifier: BSD-3-Clause
;;;; SBCL x86-64: one bit per odd candidate, held in native 64-bit words.
;;;; Dense/sparse unrolling follows Mike Barber and GordonBGood's approach
;;;; in PrimeRust/solution_1; see EXPERIMENT.md for provenance and measurements.
;;;; No prime list or sieve result is precomputed: every call makes fresh state.
(defpackage #:prime-candidate
  (:use #:cl)
  (:export #:make-sieve #:run-sieve #:primep #:count-primes #:*tags* #:*name*))
(in-package #:prime-candidate)
(declaim (optimize (speed 3) (safety 0) (debug 0)))
(defparameter *name* "echologie-cl-kernels129")
(defparameter *tags* "algorithm=base,faithful=yes,bits=1")
(deftype words () '(simple-array (unsigned-byte 64) (*)))
(defclass word-sieve ()
  ((limit :initarg :limit :reader sieve-limit :type fixnum)
   (bits :initarg :bits :reader sieve-bits :type words)))
(defun make-sieve (limit)
  "Allocate a fresh object and runtime-sized odd-candidate array."
  (check-type limit (integer 0 #.most-positive-fixnum))
  (let ((bits (make-array (ceiling (ceiling limit 2) 64)
                          :element-type '(unsigned-byte 64) :initial-element 0)))
    (declare (type words bits))
    (when (plusp (length bits)) (setf (aref bits 0) 1))
    (make-instance 'word-sieve :limit limit :bits bits)))
(declaim (inline marked-p))
(defun marked-p (bits index)
  (declare (type words bits) (type fixnum index))
  (logbitp (logand index 63) (aref bits (ash index -6))))

;; Local byte update for the bounded sparse tail.
(defun or-byte! (sap offset mask)
  (declare (type sb-sys:system-area-pointer sap)
           (type (signed-byte 64) offset) (type (unsigned-byte 8) mask))
  (setf (sb-sys:sap-ref-8 sap offset)
        (logior (sb-sys:sap-ref-8 sap offset) mask))
  (values))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown or-byte! (sb-sys:system-area-pointer (signed-byte 64) (unsigned-byte 8))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (or-byte!)
    (:translate or-byte!)
    (:policy :fast-safe)
    (:args (sap :scs (sb-vm::sap-reg)) (offset :scs (sb-vm::signed-reg)))
    (:arg-types sb-vm::system-area-pointer sb-vm::signed-num (:constant (unsigned-byte 8)))
    (:info mask)
    (:generator 1
      (sb-assem:inst or :byte (sb-vm::ea 0 sap offset) mask))))


(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown sparse-kernel! (sb-sys:system-area-pointer (unsigned-byte 64) (unsigned-byte 64) (unsigned-byte 64) (integer 1 15))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (sparse-kernel!)
    (:translate sparse-kernel!) (:policy :fast-safe)
    ;; Keep inputs live until all temporary-register computations finish.
    (:args (sap :scs (sb-vm::sap-reg) :to :save)
           (blocks :scs (sb-vm::unsigned-reg) :to :save)
           (q :scs (sb-vm::unsigned-reg) :to :save)
           (step :scs (sb-vm::unsigned-reg) :to :save))
    (:arg-types sb-vm::system-area-pointer sb-vm::unsigned-num sb-vm::unsigned-num sb-vm::unsigned-num (:constant (integer 1 15)))
    (:info residue)
    (:temporary (:sc sb-vm::sap-reg) ptr)
    (:temporary (:sc sb-vm::unsigned-reg) remaining q3 q5 q7)
    (:generator 1
      (let ((again (sb-assem:gen-label)) (done (sb-assem:gen-label)))
        (sb-vm::move ptr sap)
        (sb-vm::move remaining blocks)
        (sb-assem:inst test remaining remaining)
        (sb-assem:inst jmp :z done)
        (sb-assem:inst lea q3 (sb-vm::ea 0 q q 2))
        (sb-assem:inst lea q5 (sb-vm::ea 0 q q 4))
        (sb-assem:inst lea q7 (sb-vm::ea 0 q3 q 4))
        (sb-assem:emit-label again)
        (loop for k below 8 for index in (list nil q q q3 q q5 q3 q7)
              for scale in '(1 1 2 1 4 1 2 1)
              for carry = (floor (+ (floor residue 2) (* k (mod residue 8))) 8)
              for mask = (ash 1 (mod (+ (floor residue 2) (* k residue)) 8))
              do (sb-assem:inst or :byte (sb-vm::ea carry ptr index scale) mask))
        (sb-assem:inst add ptr step)
        (sb-assem:inst dec remaining)
        (sb-assem:inst jmp :nz again)
        (sb-assem:emit-label done)))))
(defmacro define-kernel-resetters ()
  `(progn
     ,@(loop for r from 1 to 15 by 2 for name = (intern (format nil "SPARSE-~D" r))
             collect
             `(defun ,name (bits nbytes factor)
                (declare (type words bits) (type fixnum nbytes) (type (integer 3 2147483647) factor))
                (let* ((first (ash factor -4)) (start (* first factor)) (q (ash factor -3))
                       (blocks (floor (- nbytes start) factor))
                       (tail (+ start first (* blocks factor))))
                  (declare (type (unsigned-byte 59) first start q blocks tail))
                  (sb-sys:with-pinned-objects (bits)
                    (let ((sap (sb-sys:vector-sap bits)))
                      (sparse-kernel! (sb-sys:sap+ sap (+ start first)) blocks q factor ,r)
                      ,@(loop for k below 8
                              for carry = (floor (+ (floor r 2) (* k (mod r 8))) 8)
                              for mask = (ash 1 (mod (+ (floor r 2) (* k r)) 8))
                              collect `(let ((index (+ tail (* ,k q) ,carry)))
                                         (declare (type (unsigned-byte 59) index))
                                         (when (< index nbytes) (or-byte! sap index ,mask)))))))
                nil))))
(define-kernel-resetters)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown dense-kernel! (sb-sys:system-area-pointer (unsigned-byte 64) (integer 3 129))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (dense-kernel!)
    (:translate dense-kernel!) (:policy :fast-safe)
    (:args (sap :scs (sb-vm::sap-reg) :to :save)
           (nwords :scs (sb-vm::unsigned-reg) :to :save))
    (:arg-types sb-vm::system-area-pointer sb-vm::unsigned-num (:constant (integer 3 129)))
    (:info factor)
    (:temporary (:sc sb-vm::sap-reg) ptr)
    (:temporary (:sc sb-vm::unsigned-reg) remaining mask0 mask1 mask2)
    (:generator 1
      (let* ((groups (make-array factor :initial-element nil))
             (first (* factor (floor factor 128)))
             (again (sb-assem:gen-label)) (tail (sb-assem:gen-label)))
        ;; Generate the same individual multiples as the Rust/Lisp dense loop.
        ;; Associative ORs within one word are folded during code generation.
        (dotimes (k 64)
          (let ((bit (+ (floor factor 2) (* k factor))))
            (push (ash 1 (mod bit 64)) (aref groups (floor bit 64)))))
        (let ((masks (map 'vector (lambda (bits) (reduce #'logior bits :initial-value 0)) groups)))
          (sb-assem:inst lea ptr (sb-vm::ea (* 8 first) sap))
          (sb-vm::move remaining nwords)
          (unless (zerop first) (sb-assem:inst sub remaining first))
          (when (= factor 3)
            (loop for reg in (list mask0 mask1 mask2) for value across masks
                  do (sb-assem:inst mov reg value)))
          (flet ((emit-word (i)
                   (let ((mask (aref masks i)))
                     (unless (zerop mask)
                       (cond ((= factor 3)
                              (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr)
                                             (nth i (list mask0 mask1 mask2))))
                             ((typep mask '(signed-byte 32))
                              (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) mask))
                             (t (sb-assem:inst mov mask0 mask)
                                (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) mask0)))))))
            (sb-assem:inst cmp remaining factor)
            (sb-assem:inst jmp :b tail)
            (sb-assem:emit-label again)
            (dotimes (i factor) (emit-word i))
            (sb-assem:inst add ptr (* factor 8))
            (sb-assem:inst sub remaining factor)
            (sb-assem:inst cmp remaining factor)
            (sb-assem:inst jmp :ae again)
            (sb-assem:emit-label tail)
            (dotimes (i factor)
              (unless (zerop (aref masks i))
                (let ((skip (sb-assem:gen-label)))
                  (sb-assem:inst cmp remaining i)
                  (sb-assem:inst jmp :be skip)
                  (emit-word i)
                  (sb-assem:emit-label skip)))))
          (let* ((bit (floor factor 2))
                 (clear (logxor #xffffffffffffffff (ash 1 (mod bit 64)))))
            (sb-assem:inst mov mask0 clear)
            (sb-assem:inst and :qword (sb-vm::ea (* 8 (floor bit 64)) sap) mask0)))))))
(defmacro define-dense-kernels ()
  `(progn
     ,@(loop for p from 3 to 129 by 2 collect
             `(defun ,(intern (format nil "DENSE-~D" p)) (bits)
                (declare (type words bits))
                (sb-sys:with-pinned-objects (bits)
                  (dense-kernel! (sb-sys:vector-sap bits) (length bits) ,p))
                nil))))
(define-dense-kernels)

;; Dispatch is generated for all odd factors, never a precomputed prime list.
(defmacro define-dispatchers ()
  `(progn
     (defun dense-reset (bits factor)
       (declare (type words bits) (type fixnum factor))
       (case factor ,@(loop for p from 3 to 129 by 2 collect
         `(,p (,(intern (format nil "DENSE-~D" p)) bits)))))
     (defun sparse-reset (bits factor)
       (declare (type words bits) (type fixnum factor))
       (let ((nbytes (ash (length bits) 3)))
         (declare (type fixnum nbytes))
         (case (logand factor 15)
           ,@(loop for r from 1 to 15 by 2 collect
             `(,r (,(intern (format nil "SPARSE-~D" r)) bits nbytes factor))))))))
(define-dispatchers)

(defun run-sieve (sieve)
  (let ((bits (sieve-bits sieve)) (limit (sieve-limit sieve)))
    (declare (type words bits) (type fixnum limit))
    (loop for factor fixnum from 3 to (isqrt limit) by 2
          unless (marked-p bits (ash factor -1))
            do (if (<= factor 129) (dense-reset bits factor)
                   (sparse-reset bits factor))))
  sieve)
(defun primep (sieve number)
  (declare (type fixnum number))
  (and (<= 2 number (the fixnum (sieve-limit sieve)))
       (or (= number 2)
           (and (oddp number)
                (not (marked-p (sieve-bits sieve) (ash number -1)))))))
;; Ignore padding bits in the final machine word.
(defun count-primes (sieve)
  (let* ((limit (sieve-limit sieve)) (bits (sieve-bits sieve))
         (nbits (ceiling limit 2)) (nwords (ash nbits -6))
         (tail (logand nbits 63)))
    (declare (type words bits) (type fixnum limit nbits nwords tail))
    (+ (if (>= limit 2) 1 0)
       (- nbits
          (+ (loop for i fixnum below nwords sum (logcount (aref bits i)) fixnum)
             (if (zerop tail) 0
                 (logcount (logand (aref bits nwords) (1- (ash 1 tail))))))))))
