(defpackage #:prime-candidate (:use #:cl))
(load "optimizer-snippet.lisp")
(in-package #:prime-candidate)
(declaim (optimize (speed 3) (safety 0) (debug 0)))
(defun or-test (words)
  (declare (type (simple-array (unsigned-byte 64) (*)) words))
  (let ((word (aref words 0)))
    (declare (type (unsigned-byte 64) word))
    (setf word (%word-or word 2))
    (setf word (%word-or word 16))
    (setf word (%word-or word #x8000000000000000))
    (setf (aref words 0) word))
  nil)
(disassemble 'or-test)
(let ((a (make-array 1 :element-type '(unsigned-byte 64) :initial-element 1)))
  (or-test a)
  (assert (= (aref a 0) #x8000000000000013))
  (format t "~&Generic optimizer test passed.~%"))
