;;; SBCL-specific generic peephole optimization, adapted from Robert Mayer's
;;; PrimeLisp/solution_2/PrimeSievebitops.lisp (repository contribution terms).
;;; Consecutive ORs on one register are associative, including the final flags.
;;; No sieve factors, masks, or precomputed sieve data appear in this pass.
(in-package "SB-X86-64-ASM")
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defpattern "batch: combine constant ORs" ((or) (or)) (stmt next)
    (binding* (((size1 dst1 src1) (parse-2-operands stmt))
               ((size2 dst2 src2) (parse-2-operands next)))
      (labels ((constant-value (operand)
                 (if (ea-p operand)
                     (let ((constants (asmstream-constant-vector *asmstream*)))
                       (loop for constant across constants
                             when (eq (ea-disp operand) (cdr constant))
                               return (cdar constant)))
                     operand)))
        (when (and (null (stmt-labels next)) (gpr-tn-p dst1) (location= dst2 dst1)
                   (eq size1 :qword) (eq size2 :qword)
                   (or (integerp src1) (ea-p src1))
                   (or (integerp src2) (ea-p src2)))
          (let ((value1 (constant-value src1))
                (value2 (constant-value src2)))
            (when (and (integerp value1) (integerp value2))
              (setf (stmt-operands next)
                    `(,(encode-size-prefix :qword) ,dst2
                       ,(sb-vm::constantize (logior value1 value2))))
              (add-stmt-labels next (stmt-labels stmt))
              (delete-stmt stmt)
              next)))))))
(in-package #:prime-candidate)
;;; Keep each source mark a single-bit OR; let the generic peephole combine it.
(eval-when (:compile-toplevel :load-toplevel :execute)
(sb-c:defknown %word-or ((unsigned-byte 64) (unsigned-byte 64))
    (unsigned-byte 64) (sb-c:foldable sb-c:flushable sb-c:movable) :overwrite-fndb-silently t)
)
(in-package "SB-VM")
(eval-when (:compile-toplevel :load-toplevel :execute)
(define-vop (prime-candidate::%word-or)
  (:translate prime-candidate::%word-or)
  (:policy :fast-safe)
  (:args (word :scs (unsigned-reg) :target result))
  (:arg-types unsigned-num (:constant (unsigned-byte 64)))
  (:results (result :scs (unsigned-reg)))
  (:result-types unsigned-num)
  (:info mask)
  (:generator 1
    (move result word)
    (inst or result (constantize mask))))
)
(in-package #:prime-candidate)
