(in-package #:prime-candidate)
;;; A byte OR with an immediate single-bit mask, avoiding fixnum conversions.
;;; This VOP has no sieve-specific knowledge and changes exactly the bit given.
(eval-when (:compile-toplevel :load-toplevel :execute)
(sb-c:defknown %or-byte (sb-sys:system-area-pointer (unsigned-byte 64)
                       (unsigned-byte 8)) (values)
    (sb-c:always-translatable) :overwrite-fndb-silently t)
)
(in-package "SB-VM")
(eval-when (:compile-toplevel :load-toplevel :execute)
(define-vop (prime-candidate::%or-byte)
  (:translate prime-candidate::%or-byte)
  (:policy :fast-safe)
  (:args (sap :scs (sap-reg)) (index :scs (unsigned-reg)))
  (:arg-types system-area-pointer unsigned-num (:constant (unsigned-byte 8)))
  (:info mask)
  (:generator 1 (inst or :byte (ea 0 sap index) mask)))
)
(in-package #:prime-candidate)
