(defpackage #:prime-candidate (:use #:cl))
(compile-file "or-byte-snippet.lisp" :output-file ".build/or-byte.fasl")
(load ".build/or-byte.fasl")
(in-package #:prime-candidate)
(declaim (optimize (speed 3) (safety 0) (debug 0)))
(defun or-byte-test (sap index)
  (declare (type sb-sys:system-area-pointer sap) (type (unsigned-byte 64) index))
  (%or-byte sap index 2))
(disassemble 'or-byte-test)
(let ((a (make-array 2 :element-type '(unsigned-byte 64) :initial-element 0)))
  (sb-sys:with-pinned-objects (a)
    (or-byte-test (sb-sys:vector-sap a) 9))
  (assert (= (aref a 1) 512))
  (format t "~&OR-byte compiled/loaded unit test passed.~%"))
